sudo: false
language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
  - $HOME/.yarn-cache
  - node_modules
script:
  - npm test
  - npm run predeploy
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
      branch: master
